### ISSUE TITLE
[Bug] `Cannot add property pluginUrl, object is not extensible`

### ISSUE THREAD

**Issue by ThomasEricB** [Benature/obsidian-share-my-plugin-list#1] opened 2024-02-19 13:55 UTC
Weirdly it does not activate it for me. Tried as a list and table. No clue.

Edit: video below.

**Comment by ThomasEricB** [comment] 2024-02-19 15:44
@Benature Thank you for quickly replying! First of all, apologies for not sharing a screenshot or video of the problem sooner, I was at my remote setup at university so I couldn't just do it yet. Here the video I recorded with the console open: 

https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/d248f97e-a6dd-4aa3-92f6-33ddb99857c7

And also here is a screenshot of the console:

![TYmUrKHguy](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/97425803-aef1-473a-a195-54bebf65b565)

**Comment by Benature** [comment] 2024-02-19 18:51
Hi, seems like one of your installed plugins has a strange `manifest.json`? 

To better debug this issue, I need you to update [main.js](https://www.transfernow.net/dl/20240219gUOrAzyH) in your Obsidian Vault. (the file link is valid for 7 days)
This new file will output every plugin so that I can know which plugin caused the error in the console. Then I may be able to reproduce this error in vault.

After you replace the `main.js`, run the plugin's command again, and take a screenshot near the error in the console, thank you.

**Comment by ThomasEricB** [comment] 2024-02-19 19:36
This was the error:

![Obsidian_e05UEe6Bsf](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/a93d6692-1d93-439c-b3a9-3981e3c51816)

Then I disabled the plugin and continued, each time with a different result:

![Obsidian_VYkIcHYWxM](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/800d4a16-044f-4af1-aba8-72edf61094a8)

![Obsidian_C4ZOrtBh8Y](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/b3199343-6b61-44e0-ab85-cae0b6a6e5c9)

![Obsidian_B7j4ylOUht](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/0ad75a40-a72b-4043-986d-e7186eb55095)

![Obsidian_m6JfEfT7cJ](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/b7542d5f-9356-4c98-a646-115149b4d2e4)

![Obsidian_8BfIidQ8qU](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/9cb179a4-ada1-4640-889a-7adb2e072011)

![Obsidian_37Ecn1k6ir](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/4e903757-a098-4a9f-bbe7-b91a66602f1c)

![Obsidian_30Rfu2hvzM](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/21562ac7-ea62-4984-b93f-ced733e6cb96)

![Obsidian_7kTqPrQL6u](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/f75fbffb-016b-4db4-9e4b-66c4cd9b031c)

![Obsidian_p5j5dBTBTs](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/c4525afd-e40d-47a3-a198-f4ea4172adbe)

![Obsidian_oEF3k972QC](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/aee0206f-c37f-4024-afd2-a8ab80cc4ee5)

![Obsidian_HkpruleTYH](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/3bb0eb1d-1eb9-497a-9b4e-6fa85540631a)

![Obsidian_EEx9zym9GW](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/7b91563a-c5b6-42c2-ab47-3e0656d43cf8)

I stopped here @Benature . I am guessing that your plugin had a limit of the amount of plugins it can fetch and the limit is 127... As you can see it was literally stopping at the plugins next to each other in line:

![Obsidian_f9KJVaPjYN](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/74ea77f2-57a2-44e4-ac6a-f0221086832f)

![Obsidian_zGbHlvVimL](https://github.com/Benature/obsidian-share-my-plugin-list/assets/9662095/e9ed9253-679f-4956-9474-63009ba230eb)

**Comment by Benature** [comment] 2024-02-20 02:54
This problem seems a bit tricky. Is it OK that you compress `.obsidian/plugins` folder and send me? So that I may reproduce the problem.

And please tell me your Obsidian.app version and OS (win or mac).

**Comment by Benature** [comment] 2024-02-20 04:24
Or you may unfold the output first, maybe we can find some differences between the successful plugin and the failed plugin. Like missing `manifest` attribution?
![image](https://github.com/Benature/obsidian-share-my-plugin-list/assets/35028647/44e793fd-b86a-4c44-99ae-a18f53671d58)

Here's one of the output screenshot
<img width="421" alt="image" src="https://github.com/Benature/obsidian-share-my-plugin-list/assets/35028647/a3ef2bb4-f4dc-4125-86dc-b68a5a626656">

---

Another question is that, before the error, were there some plugins that did not cause the error? Since your every screenshot only contains one plugin.

**Comment by ThomasEricB** [comment] 2024-02-20 10:44
> That's quite strange, plugins like `Advanced URI` are disabled but are somehow known by my plugin, which is not expected.

No I disabled them AFTER they appeared in the console.

**Comment by Benature** [comment] 2024-03-02 06:34
The third option: update the plugin to v0.1.0, this version should generate a plugin list with successfully loaded plugins. Plugins that failed to be read will be outputted in the console.

**Comment by ksdavidc** [comment] 2024-04-04 00:44
I recently started getting this as well. I am using version 3.0 of the plugin.  attached are log files.
[obsidian.md-1712191146386.log](https://github.com/Benature/obsidian-share-my-plugin-list/files/14859960/obsidian.md-1712191146386.log)
[obsidian.md-1712191350145.log](https://github.com/Benature/obsidian-share-my-plugin-list/files/14859961/obsidian.md-1712191350145.log)

will try downgrading to v2.0

**Comment by ksdavidc** [comment] 2024-04-04 00:47
can't downgrade via BRAT as main.js is missing...

**Comment by ksdavidc** [comment] 2024-04-04 00:52
version 0.2.1 still works.

**Comment by Benature** [comment] 2024-04-04 02:18
@ksdavidc Hi, what is your Obsidian version, and which platform you are using?

I cannot reproduce the bug. But I update v0.3.1 to try to avoid the error in your log. Please have a test.

**Comment by ksdavidc** [comment] 2024-04-04 07:35
I am using mac. Here is a crazy test vault that I use to test random plugins, none of which appear when I use SMP. But I get the same results even with more normal vaults.
I did create an empty vault from naught, and that worked, so it is working out of the box, and is likely a plugin conflict...but my best attempt to figure out which has been to no avail. 

[test share my vault.zip](https://github.com/Benature/obsidian-share-my-plugin-list/files/14862937/test.share.my.vault.zip)

Good luck!

SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.8
	Operating system: Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 23.4.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: AnuPpuccin v1.4.5
	Snippets enabled: 14
	Restricted mode: off
	Plugins installed: 187
	Plugins enabled: 162
		1: Divide & Conquer v1.0.0
		2: Admonition v10.2.0
		3: Advanced Slides v1.20.0
		4: Tidy Footnotes v0.1.1
		5: Dataview v0.5.66
		6: Kanban v1.5.3
		7: Key-Value List v1.7.0
		8: LanguageTool Integration v0.3.7
		9: Lapel v0.1.1
		10: Link Tree v1.0.0
		11: Links v1.14.4
		12: Linter v1.23.2
		13: List Callouts v1.2.7
		14: Local Images Plus v0.15.9
		15: Local REST API v2.3.0
		16: MAKE.md v0.9.7
		17: Markdown Formatting Assistant v0.4.1
		18: Markdown Table Editor v0.3.1
		19: Markmind v1.9.5
		20: Marp Slides v0.45.5
		21: Meta Bind v1.0.2
		22: Tasks v6.2.0
		23: Advanced Tables v0.21.0
		24: Another Quick Switcher v11.2.2
		25: Any Block v2.2.0
		26: Automatic Table Of Contents v1.3.2
		27: Better Command Palette v0.17.1
		28: Better Export PDF v1.7.0
		29: Better footnote v1.0.1
		30: Better PDF 2 v2.0.3
		31: Better Search Views v0.2.2
		32: Better Word Count v0.10.1
		33: BRAT v0.8.4
		34: Calendar v1.5.10
		35: CardBoard v0.7.9
		36: CodeBlock Tabs v1.0.0
		37: Crumbs v0.1.2
		38: Copy document as HTML v0.6.0
		39: Copy as HTML v1.1.3
		40: Convert url to preview (iframe) v0.5.0
		41: Commander v0.5.1
		42: Colorful Tag v1.3.2
		43: Colored Tags Wrangler v0.19.3
		44: CSV Table v1.2.0
		45: Custom Classes v2.6.1
		46: Custom Frames v2.4.7
		47: Dangling links v0.3.0
		48: DataLoom v8.15.12
		49: Digital Garden v2.56.2
		50: Doubleshift v2.2.1
		51: Dynamic Table of Contents v0.0.27
		52: Dynbedded v1.0.0
		53: Easy toggle sidebars v2.0.1
		54: Editing Toolbar v2.4.10
		55: Emoji Toolbar v0.4.1
		56: Enhanced tables v1.0.5
		57: Enhancing Export v1.10.4
		58: Excalidraw v2.1.1
		59: Extract PDF Annotations v1.0.4
		60: Extract url content v0.12.1
		61: File Diff v1.1.1
		62: File Explorer Note Count v1.2.1
		63: File Info Panel v1.3
		64: File Tree Alternative Plugin v2.3.4
		65: Find & Replace in Selection v1.1.0
		66: floating toc v2.4.7
		67: Find orphaned files and broken links v1.10.0
		68: Focus and Highlight v1.3.2
		69: Folder Note Core v1.3.5
		70: Footlinks v0.1.7
		71: Footnote & Citation Indicator v0.3.5
		72: Footnote Shortcut v0.1.3
		73: Garble Text v1.2.0
		74: Get Info v1.1.0
		75: HelpMate v1.0.6
		76: Hide Sidebars on Window Resize v1.1.0
		77: Highlightr v1.2.2
		78: Hotkey Helper v0.3.18
		79: Wrap with shortcuts v1.3.0
		80: Wordy v1.3.1
		81: Underline v1.3.0
		82: Toggle Case v1.1.0
		83: Time Ruler v2.3.0
		84: Theme Toggler v1.0.1
		85: Theme Picker v1.0.8
		86: Text Snippets v0.1.2
		87: Text Extractor v0.5.1
		88: Text expand v0.11.4
		89: Templater v2.2.3
		90: Tagged Documents Viewer v1.0.2
		91: Task Collector (TC) v1.0.17
		92: TagFolder v0.18.6
		93: Tag Wrangler v0.6.1
		94: Tag Summary v2.1.5
		95: Tag Project v0.3.1
		96: Tag Page Preview v0.0.12
		97: Tag & Word Cloud v1.4.1
		98: Table of Contents v0.2.0
		99: Table Generator v1.4.1
		100: Syncthing Integration v2.2.0
		101: Surfing v0.9.5
		102: Studier v1.0.1
		103: Style Settings v1.0.8
		104: Strange New Worlds (SNW) v1.2.5
		105: Snippetor v0.4.4
		106: Show Current File Path v0.5.2
		107: Sheets Extended v1.2.10
		108: Share Note v0.8.7
		109: Share my plugin list v0.3.2
		110: Settings Search v1.3.10
		111: Scratchblocks v0.0.1
		112: Reveal Active File Button v2.0.3
		113: Remotely Save v0.4.14
		114: Reminder v1.1.15
		115: Relation Pane v0.0.5
		116: Related Notes Finder v1.1.0
		117: Regex Find/Replace v1.2.0
		118: ReadItLater v0.4.0
		119: Quoth v0.7.1
		120: Quiet Outline v0.3.25
		121: QuickAdd v1.8.1
		122: Quick Tagger v2.2.3
		123: Quick Switcher++ v4.0.0
		124: Quick Explorer v0.2.8
		125: Query Control v0.6.0
		126: Projects v1.17.2
		127: Plugin Update Tracker v1.5.2
		128: Plugin Groups v2.1.0
		129: Pluck v1.0.1
		130: Paste URL into selection v1.7.0
		131: Pandoc Plugin v0.4.1
		132: OZ Calendar v0.3.4
		133: Open with v0.3.2
		134: Open Plugin Settings v1.3.2
		135: Open Link With v0.1.10
		136: Open Gate v1.11.6
		137: Omnisearch v1.21.1
		138: ObsidianTweaks v0.4.0
		139: Obsidian42 - Text Transporter v1.0.4
		140: Obsidian TODO | Text-based GTD v0.2.7
		141: Obsidian Query Language v2.1.1
		142: Obsidian Columns v1.5.2
		143: Obsidian asciimath v0.7.0
		144: Number Headings v1.16.0
		145: Note Refactor v1.8.2
		146: Natural Language Dates v0.6.2
		147: MySnippets v1.2.3
		148: Multiple Notes Outline v0.5.1
		149: Mind Map v1.1.0
		150: Local File Interface v0.1.0
		151: Just Share Please v0.1.5
		152: Inline Admonitions v1.2.0
		153: Imgur v2.5.2
		154: Image Upload Toolkit v0.5.2
		155: Image in Editor v2.2.6
		156: Iconize v2.11.5
		157: Icon Shortcodes v0.9.7
		158: HTML Tabs v1.1.0
		159: Blockier v1.0.3
		160: Image2LaTEX v1.1.0
		161: Tasks Calendar Wrapper v0.2.9
		162: Thino v2.3.61

**Comment by Benature** [comment] 2024-04-04 12:51
Hi @ksdavidc , thanks for the test vault, I reproduced the bug. I've update v0.3.3, it works well in the test vault. Please have a test :)

**Comment by ksdavidc** [comment] 2024-04-04 13:07
Bingo! nice work. Appreciate it. :-)

**Comment by Benature** [comment] 2024-04-04 13:56
> Bingo! nice work. Appreciate it. :-)

Nice to know that! :)

The bug `Cannot add property pluginUrl, object is not extensible` should be fixed and the issue will be closed. For any who have the bug after version 0.3.3, please feel free to comment in this issue.

**Closed by Benature** 2024-04-04 13:56 UTC
Labels: bug

**Comment by ksdavidc** [comment] 2025-05-22 20:49
I am sad to report that this bug has returned.  log attached. (using version 0.3.3)

[obsidian.md-1747946745311.log](https://github.com/user-attachments/files/20400400/obsidian.md-1747946745311.log)

**Comment by ksdavidc** [comment] 2025-05-22 20:55
It seems to be related to updating once Obsidian is started. Unchecking that prevents the error, and no errror on regular file generation. Perhaps it needs to wait a bit longer before doing the update?
